FROM openjdk:11
MAINTAINER Piyush<piyush@gmail.com>
VOLUME /tmp
EXPOSE 8080
ARG JAR_FILE=target/springdemoapp-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} spring-demo.jar
ENTRYPOINT ["java","-jar","/spring-demo.jar"]

